### ISSUE TITLE
Files outdated and can be replaced by official helm charts

### ISSUE THREAD

**Issue by DJM-FDC** [stackitcloud/kubernetes-prometheus#3]
Hey,
Seems like the information here:
https://docs.stackit.cloud/stackit/en/monitoring-of-stackit-ske-argus-78185340.html
and in this repo is quite outdated.

instead of using the files in this repo one could use helm to archive the same, but officially maintained and simpler to update:
```
#!/bin/bash
set -o pipefail

# export argus username/password/url before use
context_flag="name-of-ur-context"
helm --kube-context "$context_flag" repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm --kube-context "$context_flag" repo update
helm --kube-context "$context_flag" upgrade --install stackit prometheus-community/prometheus -f values.yaml \
  --set server.remoteWrite[0].url="$ARGUS_PUSH_METRIC_URL" \
  --set server.remoteWrite[0].basic_auth.username="$ARGUS_USERNAME" \
  --set server.remoteWrite[0].basic_auth.password="$ARGUS_PASSWORD"
```
and make use of values.yaml file:
```
configmapReload:
  prometheus:
    enabled: false
server:
  remoteWrite:
    - url: "$ARGUS_PUSH_METRIC_URL"
      basic_auth:
        username: "$ARGUS_USERNAME"
        password: "$ARGUS_PASSWORD"
      queue_config:
        max_shards: 50
        capacity: 5000
        max_samples_per_send: 500
        batch_send_deadline: 5s
  persistentVolume:
    enabled: false
  service:
    enabled: false
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
```
Additionally the part in the [documentation](https://docs.stackit.cloud/stackit/en/monitoring-of-stackit-ske-argus-78185340.html) referring to creating ARGUS credentials can now be simplified by using the portal going to the project service and ARGUS cluster. On the panel on the right you can simply press: _+ Create credentials_

Hope this helps to get the documentation updated and this repo up to date :)
